### ISSUE TITLE
Statements are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by CrispyBacon1999** [Luuk-Dev/DiscordAudio#1]
Getting the error `node_modules/discordaudio/index.d.ts(41,2): error TS1036: Statements are not allowed in ambient contexts.` when building with typescript v4.5.4.  Seems to just be an issue with the definition file. 

I'm also getting
```
node_modules/discordaudio/index.d.ts(244,39): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
node_modules/discordaudio/index.d.ts(351,35): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
node_modules/discordaudio/index.d.ts(374,63): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
```

**Comment by Luuk-Dev** [comment]
Hi,

Thank you for reporting this error. This is a bug in the typings file. I'll try to upload a patch today. I'll tell you once I've uploaded it.

Regards,

Luuk

**Comment by Luuk-Dev** [comment]
Hi,

I've just uploaded a new version which should work. I'm closing this issue for now, you can always re-open it if there is something wrong. Have a happy new year.

Regards,

Luuk
