### ISSUE TITLE
Forgot to add stateChange to subscribe.

### ISSUE THREAD

**Issue by JonathanPTM** [Luuk-Dev/DiscordAudio#6]
You forgot to add;
`globals[this.channel.id].get(`connection`).on('stateChange', (oldState, newState) => {
                    if(oldState.status === voice.VoiceConnectionStatus.Ready && newState.status === voice.VoiceConnectionStatus.Connecting){
                        globals[this.channel.id].get(`connection`).configureNetworking();
                    }
                });`
To the connection.subscribe() method.

**Comment by Luuk-Dev** [comment]
In which file did I forgot this exactly?

**Comment by JonathanPTM** [comment]
In src/classes/connection.js.

The `play` method has it, only the `subscribe` method doesn't.
https://github.com/Luuk-Dev/DiscordAudio/blob/main/src/classes/connection.js#L196

**Comment by Luuk-Dev** [comment]
I've uploaded a new version which has a `stateChange` event listener in the `subscribe` class. Have a nice day!
